/** Textos da UI em português (QA Tool MVP) */
export const strings = {
  appName: 'QA Tool',
  auth: {
    loginSubtitle: 'Inicia sessão para continuar',
    mockHintA11y: 'Dica de credenciais de demonstração',
    mockHintPrefix: 'Demonstração:',
    emailLabel: 'E-mail',
    emailPlaceholder: 'nome@luby.co',
    passwordLabel: 'Palavra-passe',
    passwordPlaceholder: '••••••••',
    signIn: 'Entrar',
    signInHint: 'Valida as credenciais e abre o painel principal',
    invalidCredentials: 'E-mail ou palavra-passe incorretos. Usa a conta de demonstração.',
    errorTitle: 'Não foi possível entrar',
    goToRegister: 'Cadastrar novo QA',
    register: {
      backA11y: 'Voltar ao ecrã de início de sessão',
      backToLoginShort: '← Voltar ao login',
      backToLogin: 'Ir para o login',
      title: 'Cadastro de QA',
      subtitle: 'Dados para integração futura com a equipa — por agora só local.',
      fullName: 'Nome completo',
      fullNamePh: 'O teu nome',
      lubyEmail: 'E-mail Luby',
      lubyEmailPh: 'nome@luby.co',
      seniorityLabel: 'Senioridade',
      seniority: {
        intern: 'Estágio',
        junior: 'Júnior',
        mid: 'Pleno',
        senior: 'Sénior',
        lead: 'Lead',
        principal: 'Principal',
      },
      city: 'Cidade',
      cityPh: 'Ex.: Porto',
      primaryFocus: 'Foco principal',
      primaryFocusPh: 'Ex.: testes manuais, API, mobile…',
      submit: 'Enviar cadastro',
      submitHint: 'Valida o formulário e regista localmente (mock)',
      validationTitle: 'Formulário incompleto',
      nameInvalid: 'Indica pelo menos o nome completo.',
      emailInvalid: 'Usa um e-mail @luby.co válido.',
      cityInvalid: 'Indica a cidade.',
      successTitle: 'Pedido registado',
      successBody:
        'Por agora o cadastro é apenas local (mock). Quando a API existir, estes dados serão enviados.',
    },
  },
  tabs: {
    home: 'Início',
    projects: 'Projetos',
    learning: 'Aprendizagem',
    settings: 'Definições',
  },
  dashboard: {
    title: 'Painel',
    greeting: 'Olá',
    subtitle: 'Resumo da tua atividade de QA',
    signOut: 'Sair',
    signOutA11y: 'Terminar sessão e voltar ao login',
    metrics: {
      openQa: 'Itens QA abertos',
      activeProjects: 'Projetos ativos',
      automation: 'Cobertura automação',
      learning: 'Módulos em curso',
    },
    actions: {
      newReview: 'Nova revisão',
      viewProjects: 'Ver projetos',
    },
    feedback: {
      newReview: 'Fluxo de nova revisão (MVP).',
    },
    quickActions: 'Atalhos',
  },
  projects: {
    title: 'Projetos',
    detailTitle: 'Detalhe do projeto',
    detailBody:
      'Este ecrã demonstra navegação tipada e stack de projetos. Os dados virão da API ou Firebase em fases seguintes.',
    detailFooter: 'MVP sem chamadas de rede.',
    emptyTitle: 'Sem projetos',
    emptyDescription: 'Ainda não há projetos. Cria um no backoffice ou sincroniza mais tarde.',
    emptyCta: 'Atualizar',
    refreshError: 'Não foi possível atualizar. Tenta outra vez.',
    openDetailA11y: 'Abrir detalhe do projeto',
  },
  learning: {
    title: 'Aprendizagem',
    subtitle: 'Conteúdos para subir o nível de QA e automação',
    emptyTitle: 'Sem cursos disponíveis',
    emptyDescription: 'Os cursos aparecerão aqui quando estiverem publicados.',
    moduleA11y: 'Abrir módulo',
  },
  settings: {
    title: 'Definições',
    account: 'Conta',
    signOut: 'Terminar sessão',
    signOutHint: 'Sai da conta e volta ao ecrã de login',
    appearance: 'Aparência',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeSystem: 'Sistema',
    themeHint: 'Escolhe como o tema segue o dispositivo ou força claro/escuro.',
    about: 'Sobre',
    version: 'Versão',
    aboutBody:
      'QA Tool — gestão de QA, projetos, automação e aprendizagem. MVP alinhado às regras do repositório.',
  },
} as const;
