/** Textos da UI em português (QA Tool MVP) */
export const strings = {
  appName: 'QA Tool',
  /** Textos partilhados por modais e ações genéricas */
  common: {
    ok: 'OK',
    cancel: 'Cancelar',
  },
  auth: {
    loginSubtitle: 'Inicia sessão para continuar',
    mockHintA11y: 'Dica de credenciais de demonstração',
    mockHintPrefix: 'Demonstração:',
    emailLabel: 'E-mail',
    emailPlaceholder: 'nome@luby.co',
    passwordLabel: 'Palavra-passe',
    passwordPlaceholder: '••••••••',
    signIn: 'Entrar',
    signInHint: 'Valida as credenciais e abre o painel principal',
    invalidCredentials: 'E-mail ou palavra-passe incorretos. Usa a conta de demonstração.',
    errorTitle: 'Não foi possível entrar',
    goToRegister: 'Cadastrar novo QA',
    register: {
      backA11y: 'Voltar ao ecrã de início de sessão',
      backToLoginShort: '← Voltar ao login',
      backToLogin: 'Ir para o login',
      title: 'Cadastro de QA',
      subtitle: 'Dados para integração futura com a equipa — por agora só local.',
      fullName: 'Nome completo',
      fullNamePh: 'O teu nome',
      lubyEmail: 'E-mail Luby',
      lubyEmailPh: 'nome@luby.co',
      seniorityLabel: 'Senioridade',
      seniority: {
        intern: 'Estágio',
        junior: 'Júnior',
        mid: 'Pleno',
        senior: 'Sénior',
        lead: 'Lead',
        principal: 'Principal',
      },
      city: 'Cidade',
      cityPh: 'Ex.: Porto',
      primaryFocus: 'Foco principal',
      primaryFocusPh: 'Ex.: testes manuais, API, mobile…',
      submit: 'Enviar cadastro',
      submitHint: 'Valida o formulário e regista localmente (mock)',
      validationTitle: 'Formulário incompleto',
      nameInvalid: 'Indica pelo menos o nome completo.',
      emailInvalid: 'Usa um e-mail @luby.co válido.',
      cityInvalid: 'Indica a cidade.',
      successTitle: 'Pedido registado',
      successBody:
        'Por agora o cadastro é apenas local (mock). Quando a API existir, estes dados serão enviados.',
    },
  },
  tabs: {
    home: 'Início',
    projects: 'Projetos',
    learning: 'Aprendizagem',
    settings: 'Definições',
  },
  dashboard: {
    title: 'Painel',
    greeting: 'Olá',
    subtitle: 'Resumo da tua atividade de QA',
    signOut: 'Sair',
    signOutA11y: 'Terminar sessão e voltar ao login',
    metrics: {
      openQa: 'Itens QA abertos',
      activeProjects: 'Projetos ativos',
      automation: 'Cobertura automação',
      learning: 'Módulos em curso',
    },
    actions: {
      newReview: 'Nova revisão',
      viewProjects: 'Ver projetos',
    },
    feedback: {
      newReview: 'Fluxo de nova revisão (MVP).',
    },
    quickActions: 'Atalhos',
  },
  projects: {
    title: 'Projetos',
    detailTitle: 'Detalhe do projeto',
    detailBody:
      'Este ecrã demonstra navegação tipada e stack de projetos. Os dados virão da API ou Firebase em fases seguintes.',
    detailFooter: 'MVP sem chamadas de rede.',
    emptyTitle: 'Sem projetos',
    emptyDescription:
      'Ainda não há projetos. Usa o botão + no canto superior direito para criar um (dados locais).',
    emptyCta: 'Atualizar',
    refreshError: 'Não foi possível atualizar. Tenta outra vez.',
    openDetailA11y: 'Abrir detalhe do projeto',
    addProjectA11y: 'Adicionar novo projeto',
    clientLabelShort: 'Cliente',
    create: {
      title: 'Novo projeto',
      subtitle: 'Preenche os dados principais. A lista é guardada localmente neste dispositivo.',
      nameLabel: 'Nome',
      namePh: 'Ex.: App mobile — checkout',
      descriptionLabel: 'Descrição',
      descriptionPh: 'Resumo do âmbito e objetivos de QA…',
      clientLabel: 'Cliente',
      clientPlaceholder: 'Selecionar cliente',
      statusLabel: 'Estado',
      statusActive: 'Ativo',
      statusPaused: 'Pausado',
      statusArchived: 'Arquivado',
      submit: 'Criar projeto',
      submitHint: 'Valida e adiciona o projeto à lista local',
      validationTitle: 'Campos em falta',
      nameInvalid: 'Indica um nome para o projeto.',
      clientInvalid: 'Escolhe um cliente.',
      successTitle: 'Projeto criado',
      successBody: 'O projeto foi adicionado à tua lista (local).',
      pickerTitle: 'Cliente',
      pickerCloseA11y: 'Fechar lista de clientes',
      cancel: 'Cancelar',
    },
    dangerZone: {
      title: 'Zona de perigo',
      description:
        'Eliminar o projeto remove-o da lista neste dispositivo. Esta ação não pode ser anulada.',
      deleteProject: 'Eliminar projeto',
      deleteHint: 'Abre um diálogo de confirmação antes de remover o projeto da lista local.',
      confirmTitle: 'Eliminar projeto?',
      confirmMessage:
        'O projeto será removido da lista local. Esta ação é irreversível.',
    },
  },
  learning: {
    title: 'Aprendizagem',
    subtitle: 'Conteúdos para subir o nível de QA e automação',
    emptyTitle: 'Sem cursos disponíveis',
    emptyDescription: 'Os cursos aparecerão aqui quando estiverem publicados.',
    moduleA11y: 'Abrir módulo',
    addLearning: 'Adicionar aprendizagem',
    addLearningHint: 'Abre o formulário para guardar um título e um link',
    modalTitle: 'Novo aprendizado',
    titleLabel: 'Título',
    titlePlaceholder: 'Ex.: Artigo sobre testes de API',
    linkLabel: 'Link',
    linkPlaceholder: 'https://exemplo.com/recurso',
    save: 'Guardar',
    validationTitle: 'Dados em falta',
    titleRequired: 'Indica um título.',
    urlRequired: 'Indica um link.',
    urlInvalid: 'O link não parece válido. Inclui o domínio (ex.: https://…).',
    openLinkA11y: 'Abrir link no navegador',
    cannotOpenTitle: 'Não foi possível abrir',
    cannotOpenBody: 'Verifica o endereço ou tenta copiar o link para o navegador.',
  },
  settings: {
    title: 'Definições',
    account: 'Conta',
    signOut: 'Terminar sessão',
    signOutHint: 'Sai da conta e volta ao ecrã de login',
    appearance: 'Aparência',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeSystem: 'Sistema',
    themeHint: 'Escolhe como o tema segue o dispositivo ou força claro/escuro.',
    about: 'Sobre',
    version: 'Versão',
    aboutBody:
      'QA Tool — gestão de QA, projetos, automação e aprendizagem. MVP alinhado às regras do repositório.',
  },
} as const;
